# h     seek -10 exact
# l     seek  10 exact
# j     seek -2 exact
# k     seek  2 exact

a     seek -10 exact
d     seek  10 exact
q multiply speed 1/1.2
e multiply speed 1.2

i cycle-values vf "negate" ""
