source-file ~/.config/tmux/tmux.conf

unbind -T pane-mode n 
unbind -T pane-mode N 

#                

set -g status-left ""

set -g status-right ""

set -g window-status-current-format ""\
"#[fg=green,bg=default]"\
"#[fg=colour255,bg=green]   #S   "\
"#[fg=green,bg=default]"
