source-file ~/.config/tmux/tmux.conf

unbind -T pane-mode n 
unbind -T pane-mode N 

#                

set -g status-left ""\
"#[fg=colour19,bg=default]"\
"#[fg=white,bg=colour19] #S "\
"#[fg=colour19,bg=colour18]"\
"#[fg=colour241,bg=colour18] #{=24:server_sessions} "\
"#[fg=colour18,bg=default]"\
"#[fg=green,bg=default] #{=24:user}"\
"#[fg=white,bg=default] * "\
"#[fg=colour239,bg=default]#{=24:host}"

set -g status-right ""\
"#[fg=colour239,bg=default] #{=12:pane_title} "\
"#[fg=colour18,bg=default]"\
"#[fg=colour241,bg=colour18] #{=8:pane_current_command} "\
"#[fg=colour19,bg=colour18]"\
"#[fg=white,bg=colour19] #{=-16:pane_current_path} "\
"#[fg=colour19,bg=default]"

set -g window-status-format ""\
"#[fg=black,bg=default] "\
"#[fg=green,bg=default]#I:#W"\
"#[fg=white]#{?window_flags,#F, }"\
"#[fg=black,bg=default] "

set -g window-status-current-format ""\
"#[fg=green,bg=default]"\
"#[fg=colour255,bg=green]#I:#W#{?window_flags,#F, }"\
"#[fg=green,bg=default]"
